blueprint:
  name: Blueprint Variable Test
  author: broyuken
  homeassistant:
    min_version: 2024.11.0
  description: |
    ## Variable Test
  domain: automation
  source_url: https://github.com/broyuken/HA_blueprints/blob/main/Frigate_Camera_Notifications/testdoorbellframework.yaml
  input:
    doorbell:
      name: |
        # Doorbell Configuration
      description: These are doorbell specific Options. If you select these options, this automation should ONLY be used for doorbell presses. Create another automation with this blueprint for motion notifications.
      icon: mdi:doorbell-video
      collapsed: false
      input:
        frigate_doorbell_event_name:
          name: Frigate Doorbell Event Name (Optional)
          description: |
            The name of the event you want created in Frigate when a doorbell press occurs
            e.g. visitor
            This name must be entered exactly the same in the object filter under the "Filters" heading
          default: ""
        doorbell_pressed_entity:
          name: Doorbell Pressed Entity
          description: |
            This is the entity that changes from off to on when the doorbell is pressed
          selector:
            entity:
              filter:
                domain: input_boolean
              multiple: true
    filters:
      name: |
        # Filters
      description: These help limit when or what you are notified about.
      icon: mdi:filter
      collapsed: true
      input:
        labels:
          name: Object Filter (Optional)
          description: Specify objects you wish to be notified about. Enter or select one object at a time.
          default: ""
          selector:
            select:
              options:
                - person
                - dog
                - cat
                - car
                - package
                - bird
              multiple: true
              custom_value: true
mode: parallel
trigger_variables:
  frigate_doorbell_event_name: !input frigate_doorbell_event_name
triggers:
  - trigger: mqtt
    topic: frigate/reviews
    payload: "on"
    value_template: >
      {{ 'on' if frigate_doorbell_event_name in value.after.data.objects else 'off' }}
    id: frigate-event
  - trigger: state
    entity_id: !input doorbell_pressed_entity
    id: doorbell-pressed
    from: "off"
    to: "on"
variables:
  frigate_doorbell_event_name: !input frigate_doorbell_event_name
  input_labels: !input labels
  #labels: "{{ (input_labels + ([] if frigate_doorbell_event_name == '' else [frigate_doorbell_event_name] )) | list | lower }}"
  labels: "{{ input_labels | list | lower }}"
actions:
  - action: persistent_notification.create
    data:
      message: |
        Doorbell Event Name: {{ frigate_doorbell_event_name }}
        objects: {{ trigger.payload_json.after.data.objects }}
        value_template: {{ 'on' if frigate_doorbell_event_name in trigger.payload_json.after.data.objects else 'off' }}
        
